### PR TITLE
Added OpenCHAMI middleware and updated go deps

### PR DESCRIPTION
**Pull request by davidallendj**
Addresses #46 by adding the OpenCHAMI middleware.

### CODE REVIEW

**Comment by synackd** [comment]
Looks like the unit tests are failing:

> Error: boot-script-service/routers.go:87:61: cannot use tokenAuth (variable of type *"github.com/OpenCHAMI/jwtauth/v5".JWTAuth) as *"github.com/go-chi/jwtauth/v5".JWTAuth value in argument to openchami_authenticator.AuthenticatorWithRequiredClaims

**Comment by davidallendj** [comment]
> Looks like the unit tests are failing:
> 
> > Error: boot-script-service/routers.go:87:61: cannot use tokenAuth (variable of type *"github.com/OpenCHAMI/jwtauth/v5".JWTAuth) as *"github.com/go-chi/jwtauth/v5".JWTAuth value in argument to openchami_authenticator.AuthenticatorWithRequiredClaims

Yep, I'm going to change the import to use the OpenCHAMI jwtauth.

**Comment by synackd** [comment]
Uh oh, we might have broken some etcd stuff:
```
GOOS=linux GOARCH=amd64 go build -v -tags musl  -o boot-script-service ./cmd/boot-script-service/
github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
github.com/coreos/etcd/clientv3/balancer/picker
# github.com/coreos/etcd/clientv3/balancer/picker
/root/go/pkg/mod/github.com/coreos/etcd@v3.3.27+incompatible/clientv3/balancer/picker/err.go:37:53: undefined: balancer.PickOptions
/root/go/pkg/mod/github.com/coreos/etcd@v3.3.27+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:63: undefined: balancer.PickOptions
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
/root/go/pkg/mod/github.com/coreos/etcd@v3.3.27+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:87: undefined: resolver.BuildOption
/root/go/pkg/mod/github.com/coreos/etcd@v3.3.27+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:40: undefined: resolver.ResolveNowOption
```

**Comment by davidallendj** [comment]
> Uh oh, we might have broken some etcd stuff:
> 
> ```
> GOOS=linux GOARCH=amd64 go build -v -tags musl  -o boot-script-service ./cmd/boot-script-service/
> github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
> github.com/coreos/etcd/clientv3/balancer/picker
> # github.com/coreos/etcd/clientv3/balancer/picker
> /root/go/pkg/mod/github.com/coreos/etcd@v3.3.27+incompatible/clientv3/balancer/picker/err.go:37:53: undefined: balancer.PickOptions
> /root/go/pkg/mod/github.com/coreos/etcd@v3.3.27+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:63: undefined: balancer.PickOptions
> # github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
> /root/go/pkg/mod/github.com/coreos/etcd@v3.3.27+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:87: undefined: resolver.BuildOption
> /root/go/pkg/mod/github.com/coreos/etcd@v3.3.27+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:40: undefined: resolver.ResolveNowOption
> ```

Huh? Did that happen from updating the packages? Maybe we'll just have to rollback the version for etcd if we can.

**Comment by synackd** [comment]
Yeah I think that was it.

Rolling back etcd fixes it.

```diff
diff --git a/go.mod b/go.mod
index efc6510..24a6993 100644
--- a/go.mod
+++ b/go.mod
@@ -37,7 +37,7 @@ require (
        github.com/Cray-HPE/hms-securestorage v1.13.0 // indirect
        github.com/aws/aws-sdk-go v1.55.5 // indirect
        github.com/cenkalti/backoff/v3 v3.2.2 // indirect
-       github.com/coreos/etcd v3.3.27+incompatible // indirect
+       github.com/coreos/etcd v3.3.13+incompatible // indirect
        github.com/coreos/go-semver v0.3.1 // indirect
        github.com/coreos/go-systemd v0.0.0-20191104093116-d3cd4ed1dbcf // indirect
        github.com/coreos/pkg v0.0.0-20240122114842-bbd7aa9bf6fb // indirect
```

**Comment by synackd** [comment]
(Make sure to `go mod tidy` after modifying go.mod)

**Comment by synackd** [comment]
BSS builds with the downgraded EtcD version.

**Review by synackd — APPROVED** [review]
Tested working. LGTM!

**Pull request merged**
